// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmouzYITbvtwB9Y0MiCZS1sYlb3Oz8pak',
    appId: '1:451357089870:web:8f17c00b0398e4292d231f',
    messagingSenderId: '451357089870',
    projectId: 'flutter-week5',
    authDomain: 'flutter-week5.firebaseapp.com',
    storageBucket: 'flutter-week5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCtDZBykVisYmITnXc6YD4YoIDIjM5ZQo',
    appId: '1:451357089870:android:5581187ed254702c2d231f',
    messagingSenderId: '451357089870',
    projectId: 'flutter-week5',
    storageBucket: 'flutter-week5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB27plMi59hWlDop6Xzm67TXKV8HlsPK9A',
    appId: '1:451357089870:ios:aace5986a36fd5212d231f',
    messagingSenderId: '451357089870',
    projectId: 'flutter-week5',
    storageBucket: 'flutter-week5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauthenticationanddatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB27plMi59hWlDop6Xzm67TXKV8HlsPK9A',
    appId: '1:451357089870:ios:aace5986a36fd5212d231f',
    messagingSenderId: '451357089870',
    projectId: 'flutter-week5',
    storageBucket: 'flutter-week5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseauthenticationanddatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmouzYITbvtwB9Y0MiCZS1sYlb3Oz8pak',
    appId: '1:451357089870:web:a803b9fd57270bb52d231f',
    messagingSenderId: '451357089870',
    projectId: 'flutter-week5',
    authDomain: 'flutter-week5.firebaseapp.com',
    storageBucket: 'flutter-week5.firebasestorage.app',
  );
}
